/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eveh.View;

import eveh.Class.AeronaveClass;
import eveh.Class.TipoAeronaveClass;
import eveh.controlador.Coordinador;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author ecarrizo
 */
public class EliminarAeronaveView extends javax.swing.JInternalFrame {

    /**
     * Creates new form EliminarAeronaveView
     */
    AeronaveClass a = new AeronaveClass();
    TipoAeronaveClass ta = new TipoAeronaveClass();
    
    
     Coordinador c = new Coordinador();
    
    public EliminarAeronaveView() {
        initComponents();
              
        btnEliminar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblMatricula = new javax.swing.JLabel();
        lblHv = new javax.swing.JLabel();
        lblDisponible = new javax.swing.JLabel();
        lblTipoAeronave = new javax.swing.JLabel();
        lblFabricacion = new javax.swing.JLabel();
        lblMantencion = new javax.swing.JLabel();
        lblVigencia = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Escuela de vuelo escuadrilla Halcón");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Eliminar Aeronave");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eveh/images/buscar.PNG"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel2.setText("Matricula");

        jLabel3.setText("Horas de Vuelo");

        jLabel5.setText("Disponible");

        jLabel6.setText("Tipo de Aeronave");

        jLabel4.setText("Matricula");

        jLabel8.setText("Vigencia");

        jLabel7.setText("Año de Fabricaión");

        jLabel9.setText("Proxima Mantención");

        lblMatricula.setText("jLabel10");

        lblHv.setText("jLabel11");

        lblDisponible.setText("jLabel12");

        lblTipoAeronave.setText("jLabel13");

        lblFabricacion.setText("jLabel14");

        lblMantencion.setText("jLabel15");

        lblVigencia.setText("jLabel16");

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eveh/images/eliminar.PNG"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTipoAeronave)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel4))
                                    .addComponent(jLabel5))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHv)
                                    .addComponent(lblDisponible)
                                    .addComponent(lblMatricula))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(203, 203, 203)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 39, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFabricacion)
                    .addComponent(lblMantencion)
                    .addComponent(lblVigencia))
                .addGap(69, 69, 69))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar))
                    .addComponent(jLabel1))
                .addGap(143, 143, 143))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(lblMatricula))
                                .addGap(38, 38, 38))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(lblHv)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblDisponible))
                        .addGap(38, 38, 38))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(lblTipoAeronave))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblFabricacion))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(lblMantencion))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblVigencia))))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        
        if(txtMatricula.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe Ingresar una matricula","Error",JOptionPane.ERROR_MESSAGE);
        }
        else{ 
            try {
                
                
                
                a = c.ListarAeronaveByMatricula(txtMatricula.getText());
                
                if(a.getTipoAeronave()<=0)
                {
                    btnEliminar.setEnabled(false);
                    JOptionPane.showMessageDialog(null, "No Existe Aeronave","Error",JOptionPane.ERROR_MESSAGE);
                }
                else
                {
                    btnEliminar.setEnabled(true);
                    lblMatricula.setText(a.getMatricula());
                    lblFabricacion.setText(Integer.toString(a.getAnioFabricacion()));
                    lblHv.setText(Integer.toString(a.getHorasVuelo()));
                    lblMantencion.setText(a.getFechaMantencion());
                    if(a.getDisponible()==0)
                    { lblDisponible.setText("No"); }
                    else
                    { lblDisponible.setText("Si"); }
                    if(a.getVigencia()==0)
                    { lblVigencia.setText("No"); }
                    else
                    { lblVigencia.setText("Si"); }
                    ta = c.ListarTipoAeronaveById(a.getTipoAeronave());
                    lblTipoAeronave.setText(ta.getDetalle());
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(EliminarAeronaveView.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        try {
            
            c.EliminarAeronave(a.getMatricula());
            lblMatricula.setText("");
            lblFabricacion.setText("");
            lblHv.setText("");
            lblMantencion.setText("");
            lblDisponible.setText("");
            lblVigencia.setText("");
            lblTipoAeronave.setText("");
            txtMatricula.setText(null);
            btnEliminar.setEnabled(false);
            
        } catch (SQLException ex) {
            Logger.getLogger(EliminarAeronaveView.class.getName()).log(Level.SEVERE, null, ex);
        }
      
        
        
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblDisponible;
    private javax.swing.JLabel lblFabricacion;
    private javax.swing.JLabel lblHv;
    private javax.swing.JLabel lblMantencion;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblTipoAeronave;
    private javax.swing.JLabel lblVigencia;
    private javax.swing.JTextField txtMatricula;
    // End of variables declaration//GEN-END:variables
}
