/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eveh.View;

import eveh.Class.*;
import eveh.controlador.Coordinador;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ecarrizo
 */
public class IngresoAeronaveView extends javax.swing.JInternalFrame {

    /**
     * Creates new form IngresoAeronaveView
     */
    DateFormat df = DateFormat.getDateInstance();
    Coordinador c = new Coordinador();
    HashMap<String, Integer> map1;
    HashMap<String, Integer> map2;
    HashMap<String, Integer> map3;
    
    public IngresoAeronaveView() throws SQLException {
        initComponents();
        LlenarComboTipo();
        LlenarComboVig();
        LlenarComboDisp();
    }
    
    public void LlenarComboTipo() throws SQLException{
        this.map1 = c.ComboTipo();
        cmbTipo.addItem("Seleccione Tipo Aeronave");
        for(String s : map1.keySet()){
            cmbTipo.addItem(s);
        }
    }
    
    public void LlenarComboVig() throws SQLException{
        this.map2 = c.ComboVigencia();
        cmbVigencia.addItem("Seleccione Vigencia");
        for(String s : map2.keySet()){
            cmbVigencia.addItem(s);
        }
    }

    public void LlenarComboDisp() throws SQLException{
        this.map3 = c.ComboDisponible();
        cmbDisponible.addItem("Seleccione Disponibilidad");
        for(String s : map3.keySet()){
            cmbDisponible.addItem(s);
        }
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        txtHorasVuelo = new javax.swing.JTextField();
        txtAnioFabricacion = new javax.swing.JTextField();
        cmbDisponible = new javax.swing.JComboBox<>();
        cmbTipo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFecMan = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbVigencia = new javax.swing.JComboBox<>();

        jTextField4.setText("jTextField4");

        jFormattedTextField1.setText("jFormattedTextField1");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Escuela de vuelo escuadrilla Halcón");

        jLabel1.setText("Matricula");

        txtHorasVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHorasVueloActionPerformed(evt);
            }
        });

        jLabel2.setText("Horas de Vuelo");

        jLabel3.setText("Año de Fabricaión");

        jLabel4.setText("Proxima Mantención");

        jLabel5.setText("Disponible");

        jLabel6.setText("Tipo de Aeronave");

        txtFecMan.setDateFormatString("dd/MM/yyyy");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eveh/images/guardar.png"))); // NOI18N
        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Ingresar Aeronave");

        jLabel8.setText("Vigencia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtHorasVuelo)
                                        .addComponent(txtMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                                    .addComponent(cmbDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(28, 28, 28)
                                        .addComponent(txtAnioFabricacion, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel8))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtFecMan, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 24, Short.MAX_VALUE))
                                            .addComponent(cmbVigencia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1)
                                            .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(txtHorasVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtAnioFabricacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtFecMan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(cmbVigencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addGap(52, 52, 52)
                .addComponent(jButton1)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHorasVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHorasVueloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHorasVueloActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(cmbTipo.getSelectedItem().toString() == "Seleccione Tipo Aeronave"){
            JOptionPane.showMessageDialog(null, "Debe Seleccionar Tipo de Aeronave","Error",JOptionPane.ERROR_MESSAGE);
        }else if(cmbVigencia.getSelectedItem().toString() == "Seleccione Vigencia"){
            JOptionPane.showMessageDialog(null, "Debe Seleccionar Vigencia","Error",JOptionPane.ERROR_MESSAGE);
        }else if(cmbDisponible.getSelectedItem().toString() == "Seleccione Vigencia"){
            JOptionPane.showMessageDialog(null, "Debe Seleccionar Disponibilidad","Error",JOptionPane.ERROR_MESSAGE);
        }else if(txtAnioFabricacion.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe Ingresar Año de fabricación","Error",JOptionPane.ERROR_MESSAGE);
        }else if(txtHorasVuelo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe Ingresar Horas de vuelo","Error",JOptionPane.ERROR_MESSAGE);
        }else if(txtMatricula.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe Ingresar Matricula","Error",JOptionPane.ERROR_MESSAGE);
        }else if(txtFecMan.getDate() == null){
            JOptionPane.showMessageDialog(null, "Debe Ingresar Fecha Próxima Mantención","Error",JOptionPane.ERROR_MESSAGE);
        }
        else{       
            String fechaObtenida = df.format(txtFecMan.getDate());
            AeronaveClass a = new AeronaveClass();
            a.setMatricula(txtMatricula.getText().toString());
            a.setHorasVuelo(Integer.parseInt(txtHorasVuelo.getText()));
            a.setAnioFabricacion(Integer.parseInt(txtAnioFabricacion.getText()));
            a.setFechaMantencion(fechaObtenida);
            a.setDisponible(Integer.parseInt(map3.get(cmbDisponible.getSelectedItem().toString()).toString()));
            System.out.println(map3.get(cmbDisponible.getSelectedItem().toString()).toString());
            a.setVigencia(Integer.parseInt(map2.get(cmbVigencia.getSelectedItem().toString()).toString()));
            a.setTipoAeronave(Integer.parseInt(map1.get(cmbTipo.getSelectedItem().toString()).toString()));
            try { if(c.IngresarAeronave(a)){

                txtAnioFabricacion.setText("");
                txtFecMan.setDate(null);
                txtHorasVuelo.setText("");
                txtMatricula.setText("");
                cmbDisponible.removeAllItems();
                cmbTipo.removeAllItems();
                cmbVigencia.removeAllItems();
                LlenarComboTipo();
                LlenarComboVig();
                LlenarComboDisp();
                
                }
            } catch (SQLException ex) {
                Logger.getLogger(IngresoAeronaveView.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbDisponible;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JComboBox<String> cmbVigencia;
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField txtAnioFabricacion;
    private com.toedter.calendar.JDateChooser txtFecMan;
    private javax.swing.JTextField txtHorasVuelo;
    private javax.swing.JTextField txtMatricula;
    // End of variables declaration//GEN-END:variables

    private String[] KeyValue(int typeID, String docTypeName) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
