/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eveh.View;

import com.sun.org.apache.xalan.internal.xsltc.runtime.ErrorMessages_es;
import eveh.Class.TipoAeronaveClass;
import eveh.controlador.Coordinador;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ecarrizo
 */
public class IngresoTipoAeronaveView extends javax.swing.JInternalFrame {

    
    Coordinador c = new Coordinador();
    HashMap<String, Integer> map;
    TipoAeronaveClass ta = new TipoAeronaveClass();
    /**
     * Creates new form IngresoTipoAeronaveView
     */
    public IngresoTipoAeronaveView() throws SQLException {
        initComponents();
        LlenarCombo();
    }

    public void LlenarCombo() throws SQLException{
        this.map = c.ComboVigencia();
        cbxVigencia.addItem("Seleccione Vigencia");
        for(String s : map.keySet()){
            cbxVigencia.addItem(s);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        txtDetalle = new javax.swing.JTextField();
        cbxVigencia = new javax.swing.JComboBox<>();
        btnIngresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jTextField2.setText("jTextField2");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Escuela de vuelo escuadrilla Halcón");

        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eveh/images/guardar.png"))); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Ingreso Tipo de Aeronave");

        jLabel2.setText("Tipo Aeronave");

        jLabel3.setText("Vigencia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDetalle)
                            .addComponent(cbxVigencia, 0, 162, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(81, 81, 81)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(165, 165, 165)
                            .addComponent(btnIngresar))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxVigencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(43, 43, 43)
                .addComponent(btnIngresar)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        if(txtDetalle.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Debe Ingresar Tipo de Aeronave");
        }
        else if(cbxVigencia.getSelectedItem().toString() == "Seleccione Vigencia")
        {
            JOptionPane.showMessageDialog(null, "Debe Seleccionar Vigencia");
        }
        else 
        {
            try {
                ta.setDetalle(txtDetalle.getText());
                ta.setVigencia(Integer.parseInt(map.get(cbxVigencia.getSelectedItem().toString()).toString()));
                if(c.IngresarTipoAeronave(ta))
                {
                    txtDetalle.setText("");
                }
            } catch (SQLException ex) {
                Logger.getLogger(IngresoTipoAeronaveView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_btnIngresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JComboBox<String> cbxVigencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txtDetalle;
    // End of variables declaration//GEN-END:variables
}
